services:
  sis_py:
    build:
      context: ./
      dockerfile: docker_files/Dockerfile-php
    container_name: sis_py
    restart: always
    volumes:
      - ./src:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./apache/log:/var/log/apache2/
      - ./apache/apache2.conf:/etc/apache2/apache2.conf
      - ./apache/mods-available/mpm_prefork.conf:/etc/apache2/mods-available/mpm_prefork.conf
    ports:
      - 9060:80
    networks:
      - app
    # Agregar comando post-start para desarrollo
    command: bash -c "cd /var/www/html && composer install && apache2-foreground"


networks:
  app:
    driver: bridge
