FROM php:8.0-apache

# Instalar dependencias del sistema
RUN apt-get update \
    && apt-get install -y \
       libpq-dev \
       libpng-dev \
       libjpeg62-turbo-dev \
       libfreetype6-dev \
       libyaml-dev \
       zlib1g-dev \
       unzip \
       libzip-dev \
       libmagickwand-dev --no-install-recommends \ 
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get autoremove -y

# Instalar la extensión YAML de PECL
RUN pecl install yaml \
    && docker-php-ext-enable yaml

# Configurar GD
RUN docker-php-ext-configure gd --with-freetype --with-jpeg

# Instalar extensiones PHP
RUN docker-php-ext-install pgsql pdo_pgsql gd zip

# Instalar y habilitar la extensión imagick para manipulación de imágenes
RUN pecl install imagick \
    && docker-php-ext-enable imagick

# Instalar Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r "if (hash_file('sha384', 'composer-setup.php') === 'c8b085408188070d5f52bcfe4ecfbee5f727afa458b2573b8eaaf77b3419b0bf2768dc67c86944da1544f06fa544fd47') { echo 'Installer verified'.PHP_EOL; } else { echo 'Installer corrupt'.PHP_EOL; unlink('composer-setup.php'); exit(1); }" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer

# Configurar tamaño máximo de archivo para subidas
RUN echo "upload_max_filesize = 10M;" > /usr/local/etc/php/conf.d/uploads.ini

# Habilitar el módulo rewrite de Apache
RUN a2enmod rewrite

# Establecer el punto de entrada
CMD ["apache2-foreground"]
