INSERT INTO roles (name, description) 
VALUES 
    ('admin', 'Administrador del sistema')
ON CONFLICT (name) DO NOTHING;

INSERT INTO users (
    username, 
    email, 
    password_hash, 
    first_name, 
    last_name, 
    role_id,
    email_verified
) VALUES (
    'ADMIN',
    'admin@example.com',    
    '8cb2237d0679ca88db6464eac60da96345513964', -- sha1 de '12345'
    'Administrador',
    'Del Sistema',
    (SELECT id FROM roles WHERE name = 'admin'),
    TRUE
) ON CONFLICT (username) DO NOTHING;

INSERT INTO document_type (id, "name")
VALUES
('01', 'Cédula de Identidad'),
('02', 'Cédula Extranjera'),
('03', 'Pasaporte');


INSERT INTO allergies (local_code, local_term, "type", category)
VALUES
('T63.8', 'EFECTOS TOXICOS DEL CONTACTO CON OTROS ANIMALES VENENOSOS', 'ANIMAL', 'environment'),
('T78.4', 'ALERGIA NO ESPECIFICADA', 'OTRO', 'environment'),
('T78.2', 'CHOQUE ANAFILACTICO, NO ESPECIFICADO', 'OTRO', 'environment'),
('T78.1', 'OTRA REACCION ADVERSA A ALIMENTOS, NO CLASIFICADA EN OTRA PARTE', 'ALIMENTO', 'food'),
('T88.7', 'EFECTO ADVERSO NO ESPECIFICADO DE DROGA O MEDICAMENTO', 'MEDICAMENTO', 'medication'),
('T63.4', 'EFECTO TOXICO DEL VENENO DE OTROS ARTROPODOS', 'ANIMAL', 'environment'),
('T78.3', 'EDEMA ANGIONEUROTICO', 'OTRO', 'environment'),
('J30.1', 'RINITIS ALERGICA DEBIDA AL POLEN', 'RESPIRATORIA', 'environment'),
('J45.8', 'ASMA MIXTA', 'RESPIRATORIA', 'environment'),
('J30.2', 'OTRA RINITIS ALERGICA ESTACIONAL', 'RESPIRATORIA', 'environment'),
('J30.4', 'RINITIS ALERGICA, NO ESPECIFICADA', 'RESPIRATORIA', 'environment'),
('J45.9', 'ASMA, NO ESPECIFICADO', 'RESPIRATORIA', 'environment'),
('J45.0', 'ASMA PREDOMINANTEMENTE ALERGICA', 'RESPIRATORIA', 'environment'),
('T88.1', 'OTRAS COMPLICACIONES CONSECUTIVAS A INMUNIZACION, NO CLASIFICADAS EN OTRA PARTE', 'MEDICAMENTO', 'medication'),
('Y57.9', 'EFECTOS ADVERSOS DE DROGAS O MEDICAMENTOS NO ESPECIFICADOS', 'MEDICAMENTO', 'medication'),
('T36.0', 'ENVENENAMIENTO POR PENICILINAS', 'MEDICAMENTO', 'medication'),
('T37.0', 'ENVENENAMIENTO POR OTROS ANTIINFECCIOSOS Y ANTIPARASITARIOS SISTEMICOS', 'MEDICAMENTO', 'medication'),
('T36.0', 'ENVENENAMIENTO POR ANTIBIOTICOS SISTEMICOS', 'MEDICAMENTO', 'medication'),
('T80.5', 'CHOQUE ANAFILACTICO DEBIDO A SUERO', 'MEDICAMENTO', 'medication'),
('T63.9', 'EFECTO TOXICO DEL CONTACTO CON ANIMAL VENENOSO NO ESPECIFICADO', 'ANIMAL', 'environment');


INSERT INTO public.organization
(identifier, "name", "type")
VALUES
('0004000.00010101', 'H.R. - VILLARRICA', 'HR'),
('0018000.00300201', 'HOSPITAL GENERAL BARRIO OBRERO', 'HG'),
('0010000.00010A02', 'HOSP. FUNDACION TESAI', 'IP'),
('0011000.00080229', 'HD. LIMPIO', 'HD'),
('0018000.0030A2', 'CENTRO MEDICO LA COSTA', 'HP'),
(' 456789.98765432', 'SANATORIO BRITANICO', 'HP'),
('0018000.00300A15', 'SANATORIO MIGONE', 'HP'),
('0018000.00300402', 'POLICLINICO POLICIAL', 'HE'),
('0011000.00140801', 'HOSPITAL DE CLINICAS', 'HESC'),
('0018000.00300301', 'SANIDAD MILITAR', 'HE'),
('0011000.00030703', 'IPS- CLINICA INGAVI PERIFERICA', 'IPS'),
('  456789.98765432', 'INSTITUTO DE PREVISION SOCIAL (I.P.S.)', 'IPS'),
('  456789.98765432', 'SAN CARLOS', 'HP'),
('111111.111111', 'SAN ROQUE SRL', 'HP'),
('0.1', 'HOSPITAL CABEZADURA', 'HP'),
('0.1', 'HOSPITAL CABEZADURA', 'HP'),
('0001000.00012019', 'SANATORIO LUZ Y VIDA', 'HP');


INSERT INTO public.medication
(local_code, local_term)
VALUES
('E001', 'METFORMINA'),
('E002', 'ENALAPRIL'),
('E003', 'LEVOTIROXINA'),
('E004', 'ATORVASTATINA'),
('E005', 'INSULINA GLARGINA'),
('E006', 'SALBUTAMOL'),
('E007', 'OMPERAZOL'),
('E008', 'WARFARINA'),
('E009', 'PREDNISONA'),
('E010', 'PREGABALINA'),
('E011', 'MORFINA'),
('E012', 'SALBUTAMOL'),
('E013', 'LORATADINA'),
('E014', 'ATENOLOL'),
('E015', 'CARBAMAZEPINA'),
('E016', 'RANITIDINA'),
('E017', 'ALLOPURINOL'),
('E018', 'LOSARTÁN'),
('E019', 'RIVASTIGMINA'),
('E020', 'ACIDO ACETILSALICÍLICO');


